### ISSUE TITLE
Add support for Django 3.0

### ISSUE THREAD

**Issue by David-Wobrock** [3YOURMIND/django-add-default-value#18]
After adding Django 2.2 support (https://github.com/3YOURMIND/django-add-default-value/issues/14), if would be nice to also support Django 3.0.

Since the migration linter https://github.com/3YOURMIND/django-migration-linter is keeping its dependencies up to date and uses the add-default-value lib in its tests to ensure compatibility. So running those tests with the latest Django version is becoming cumbersome.

**Comment by flixx** [comment]
@David-Wobrock done :)
