### ISSUE TITLE
Add support for multiple databases

### ISSUE THREAD

**Issue by partizaans** [3YOURMIND/django-add-default-value#19]
There is a problem when the Django project is using multiple databases with custom implemented DBRouter. There is nowhere in the `django-add-default-value` that checks `allow_migrate_model` from the base `Operation` class and that while Django's itself migration Operation classes (E.g. `RemoveField`) executes the SQL only if the migration is allowed on the given `db`.

**Comment by flixx** [comment]
Solved with https://github.com/3YOURMIND/django-add-default-value/pull/16
