### ISSUE TITLE
Properly Implement Markdown Readme

### ISSUE THREAD

**Issue by dodekeract** [3YOURMIND/django-add-default-value#3]
See https://github.com/3YOURMIND/django-add-default-value/commit/ae5f88f5bee4c67acf2b64f0ad9fd20358e951cd.

**Comment by justinline** [comment]
Fixed as of 68e160a :)

**Comment by dodekeract** [comment]
@justinline Thanks, have you found a way to test how pypi renders the readme?

**Comment by justinline** [comment]
You can use a package called twine to upload to test.pypi.org which is a mirror of pypi.org for staging.
I also found recommendations to use `wheel==31.0.0`, `setuptools>=38.6.0` and `twine>=1.11.0` for rendering markdown with twine.
