### ISSUE TITLE
Allow Django 3.2 

### ISSUE THREAD

**Issue by oscarhermoso** [3YOURMIND/django-add-default-value#30]
Hi all,

The current pip release of django-add-default-value isn't allowing installation alongside Django 3.2

```
ERROR: Cannot install Django~=3.2 and django-add-default-value==0.7.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested Django~=3.2
    django-add-default-value 0.7.0 depends on Django<3.2 and >=1.11

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
```

**Comment by David-Wobrock** [comment]
Hi @oscarhermoso 

Thanks for submitting the issue. I opened a PR to add Django 3.2 to the dependencies, and don't have an error when installing a version above that https://github.com/3YOURMIND/django-add-default-value/pull/31

**Comment by oscarhermoso** [comment]
@David-Wobrock

Thankyou for subbmitting the PR, I was going to do myself but was busy.
